accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signout/', views.signout, name='signout'),
]

chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    sent = models.DateTimeField(auto_now_add=True)


class Room(models.Model):
    name = models.CharField(max_length=150)
    user = models.ManyToManyField(User)

accounts/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.urls import reverse
from django.shortcuts import redirect


class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        return reverse('accounts:signin')


class SigninView(LoginView):
    template_name = 'accounts/signin.html'

    def get_success_url(self):
        return reverse('chat:index')


def signout(request):
    logout(request)
    return redirect('chat:index')

chat/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'chat/index.html')


def room(request, room_name):
    return render(request, 'chat/room.html', {'room_name': room_name})

accounts/templates/accounts/signin.html
{% extends "base_generic.html" %}

{% block style %}{% load bootstrap4 %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="signin-form">
            <form method="post">
                <h2>Sign in</h2>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Go</button>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base_generic.html" %}

{% block style %}{% load bootstrap4 %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="signup-form">
            <form method="post">
                <h1>Sign up</h1>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Go</button>
            </form>
        </div>
    </div>
{% endblock %}

chat/templates/chat/index.html
{% extends "base_generic.html" %}

{% block title %}Chat Rooms{% endblock %}

{% block style %}{% load bootstrap4 %}{% endblock %}

{% block javascript %}
    <script>
        function pick_room() {
            let room_name = $("#room-name-input").val()
            window.location.pathname = '/chat/' + room_name + '/';
        }
        $("#room-name-input").focus();
        $("#room-name-input").on("keyup", function(event) {
            if (event.which == 13) {
                pick_room();
            }
        });
        $("#room-name-submit").click(pick_room);
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>What chat room would you like to enter?</h1>
        <input id="room-name-input" type="text" size="100"><br>
        <input id="room-name-submit" type="button" value="Enter"><br>
    </div>
{% endblock %}

chat/templates/chat/room.html
{% extends "base_generic.html" %}

{% block title %}Chat Room{% endblock %}

{% block style %}{% load bootstrap4 %}{% endblock %}

{% block javascript %}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.username + ': ' + data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <textarea id="chat-log" cols="100" rows="20"></textarea><br>
        <input id="chat-message-input" type="text" size="100"><br>
        <input id="chat-message-submit" type="button" value="Send"><br>
        {{ room_name|json_script:"room-name" }}
    </div>
{% endblock %}

templates/base_generic.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        {% block style %}{% endblock %}
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        {% include "navigation.html" %}
        {% block content %}{% endblock %}
        {% block javascript %}{% endblock %}
    </body>
</html>

templates/navigation.html
<ul>
    <li>
        <a href="#">{{ user }}</a>
    </li>
    <li>
        <a href="{% url 'accounts:signup' %}">Sign up</a>
    </li>
    <li>
        <a href="{% url 'accounts:signin' %}">Sign in</a>
    </li>
    <li>
        <a href="{% url 'accounts:signout' %}">Sign out</a>
    </li>
</ul>